services:
  - type: web
    name: muhim-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        value: PUT_YOUR_BOT_TOKEN_HERE
        sync: false